### ISSUE TITLE
Missing function `calc_cam_scale_trans_const_scale`

### ISSUE THREAD

**Issue by luisleo526** [Jeff-sjtu/NIKI#15]
Thanks for sharing such fantastic works. 

When I was trying to run the train/validate/demo according to README.md, I got the following error:

```
Traceback (most recent call last):
  File "scripts/train.py", line 8, in <module>
    from niki.datasets.naive_dataset_temporal import (
  File "/home/ubuntu/NIKI/niki/datasets/naive_dataset_temporal.py", line 22, in <module>
    from .hp3d_dataset_temporal import hp3d_dataset_temporal
  File "/home/ubuntu/NIKI/niki/datasets/hp3d_dataset_temporal.py", line 16, in <module>
    from niki.utils.pose_utils import (calc_cam_scale_trans_const_scale,
ImportError: cannot import name 'calc_cam_scale_trans_const_scale' from 'niki.utils.pose_utils' (/home/ubuntu/NIKI/niki/utils/pose_utils.py)
```

After digging into `niki/utils/pose_utils`, I was unable to find the function `calc_cam_scale_trans_const_scale `.

Is this a bug?

**Comment by nevoliu** [comment]
> Thanks for sharing such fantastic works.
> 
> When I was trying to run the train/validate/demo according to README.md, I got the following error:
> 
> ```
> Traceback (most recent call last):
>   File "scripts/train.py", line 8, in <module>
>     from niki.datasets.naive_dataset_temporal import (
>   File "/home/ubuntu/NIKI/niki/datasets/naive_dataset_temporal.py", line 22, in <module>
>     from .hp3d_dataset_temporal import hp3d_dataset_temporal
>   File "/home/ubuntu/NIKI/niki/datasets/hp3d_dataset_temporal.py", line 16, in <module>
>     from niki.utils.pose_utils import (calc_cam_scale_trans_const_scale,
> ImportError: cannot import name 'calc_cam_scale_trans_const_scale' from 'niki.utils.pose_utils' (/home/ubuntu/NIKI/niki/utils/pose_utils.py)
> ```
> 
> After digging into `niki/utils/pose_utils`, I was unable to find the function `calc_cam_scale_trans_const_scale `.
> 
> Is this a bug?

I have encountered the same issue. Have you resolved it?

**Comment by GloryyrolG** [comment]
hi @jeffffffli @biansy000 et al.,

thx for ur great work. could u pls help on this question? thx & best, happy new year
