### ISSUE TITLE
Cannot open video for writing

### ISSUE THREAD

**Issue by XJX-187** [Jeff-sjtu/NIKI#25]
Env: Windows 10, anaconda 24.1 , python 3.8.19

sends the error:
Loading model from exp/checkpoint_49_cocoeft.pth...
Loding LGD model from exp/niki_model_28.pth
Try to use other video encoders...
Traceback (most recent call last):
  File "scripts/demo.py", line 208, in <module>
    assert write_stream.isOpened(), 'Cannot open video for writing'
AssertionError: Cannot open video for writing

**Comment by XJX-187** [comment]
now is：
Loading model from exp/checkpoint_49_cocoeft.pth...
Loding LGD model from exp/niki_model_28.pth
OpenCV: FFMPEG: tag 0x64697678/'xvid' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Try to use other video encoders...
Traceback (most recent call last):
  File "scripts/demo.py", line 208, in <module>
    assert write_stream.isOpened(), 'Cannot open video for writing'
AssertionError: Cannot open video for writing

**Comment by soltkreig** [comment]
You can comment line 208 ```assert write_stream.isOpened(), 'Cannot open video for writing'```, but I got next error:
```
Could not find encoder for codec id 27: Encoder not found
Try to use other video encoders...
ffmpeg: error while loading shared libraries: libopenh264.so.5: cannot open shared object file: No such file or directory
0it [00:00, ?it/s]
### Run Model...
0it [00:00, ?it/s]
pred_uvd  failed
pred_xyz_29  failed
pred_scores  failed
pred_sigma  failed
f  failed
pred_betas  failed
pred_phi  failed
scale_mult  failed
pred_cam_root  failed
bbox  failed
height  failed
width  failed
img_path  failed
img_sizes  failed
total_img 0
Traceback (most recent call last):
  File "scripts/demo.py", line 328, in <module>
    mean_beta = res_db['pred_betas'].mean(axis=0)
AttributeError: 'list' object has no attribute 'mean'
```

**Comment by XJX-187** [comment]
> You can comment line 208 `assert write_stream.isOpened(), 'Cannot open video for writing'`, but I got next error:
> 
> ```
> Could not find encoder for codec id 27: Encoder not found
> Try to use other video encoders...
> ffmpeg: error while loading shared libraries: libopenh264.so.5: cannot open shared object file: No such file or directory
> 0it [00:00, ?it/s]
> ### Run Model...
> 0it [00:00, ?it/s]
> pred_uvd  failed
> pred_xyz_29  failed
> pred_scores  failed
> pred_sigma  failed
> f  failed
> pred_betas  failed
> pred_phi  failed
> scale_mult  failed
> pred_cam_root  failed
> bbox  failed
> height  failed
> width  failed
> img_path  failed
> img_sizes  failed
> total_img 0
> Traceback (most recent call last):
>   File "scripts/demo.py", line 328, in <module>
>     mean_beta = res_db['pred_betas'].mean(axis=0)
> AttributeError: 'list' object has no attribute 'mean'
> ```

Perhaps you should try reinstalling ffmpeg first, as I also installed H.246 at the time. Try to ensure that either pip or conda installs all packages.
Unfortunately, I also forgot which specific modifications were made at that time.Good Luck!

**Comment by soltkreig** [comment]
Found the solution:
in scripts/demo.py
replace code from line 186 if you use full path for output folder, on:
```
savepath = f'{output}/res_{video_basename}.mp4'
savepath2d = f'{output}/res_2d_{video_basename}.mp4'
```
and 191 from:
```
write_stream = cv2.VideoWriter(
    *[info[k] for k in ['savepath', 'fourcc', 'fps', 'frameSize']])
```
to:
```
write_stream = cv2.VideoWriter(info['savepath'],  info['fourcc'], info['fps'], info['frameSize'])

```
and 426 line to:
```
res_db_path = os.path.join(f'{opt.out_dir}/', f'{video_basename}.pt')
joblib.dump(res_db, res_db_path)
```
